"""empty message

Revision ID: 0cb60b60f8b6
Revises: 966fd7437766
Create Date: 2024-08-04 07:26:21.465763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb60b60f8b6'
down_revision = '966fd7437766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('promotional_tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotional_tag', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
