"""empty message

Revision ID: 12cb9d3ce2ae
Revises: 0cb60b60f8b6
Create Date: 2024-08-10 19:54:22.180945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cb9d3ce2ae'
down_revision = '0cb60b60f8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
