"""empty message

Revision ID: 1bee1c1ec8f0
Revises: 1164b0d511b0
Create Date: 2024-07-31 08:26:47.088948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bee1c1ec8f0'
down_revision = '1164b0d511b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
