"""Add tagline to ProductCategory

Revision ID: 28025defa14a
Revises: e1271b86fd44
Create Date: 2024-08-03 05:32:20.349544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28025defa14a'
down_revision = 'e1271b86fd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagline', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.drop_column('tagline')

    # ### end Alembic commands ###
