"""Add order_day_of_week column to Order model

Revision ID: 308e31bd1934
Revises: 7ea396e4b2f1
Create Date: 2024-01-07 10:14:20.135229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308e31bd1934'
down_revision = '7ea396e4b2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.Integer(), nullable=True))
        batch_op.drop_column('order_day_of_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_day_of_week', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
