"""empty message

Revision ID: 498fb5585a64
Revises: 7bfdae957786
Create Date: 2024-09-20 12:08:05.602476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498fb5585a64'
down_revision = '7bfdae957786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_index('ix_cart_product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index('ix_cart_product_id', ['product_id'], unique=False)
        batch_op.drop_column('price')

    # ### end Alembic commands ###
