"""Add selling_price to Product model

Revision ID: 53b80731063f
Revises: 88bdf89d58ec
Create Date: 2024-08-25 13:12:28.555613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b80731063f'
down_revision = '88bdf89d58ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('selling_price')

    # ### end Alembic commands ###
