"""empty message

Revision ID: 558103834b6a
Revises: f994685f00bc
Create Date: 2024-08-22 06:24:30.500076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558103834b6a'
down_revision = 'f994685f00bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_delivery_info', schema=None) as batch_op:
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_delivery_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
