"""empty message

Revision ID: 559eecc8c085
Revises: 1bee1c1ec8f0
Create Date: 2024-07-31 10:29:46.342467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559eecc8c085'
down_revision = '1bee1c1ec8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
