"""empty message

Revision ID: 6784e8fe4fac
Revises: fd3eb767154a
Create Date: 2024-08-23 11:46:29.153095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6784e8fe4fac'
down_revision = 'fd3eb767154a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_click', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_product_click_guest_ip'), ['guest_ip'], unique=False)

    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_ip', sa.String(length=45), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_product_view_guest_ip'), ['guest_ip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_view_guest_ip'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('guest_ip')

    with op.batch_alter_table('product_click', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_click_guest_ip'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
