"""empty message

Revision ID: 72be40b7df21
Revises: daae93578397
Create Date: 2024-06-20 05:49:25.957335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72be40b7df21'
down_revision = 'daae93578397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('order')
    op.drop_table('nearest_place')
    op.drop_table('user_delivery_info')
    op.drop_table('payment')
    op.drop_table('invoice')
    op.drop_table('order_item')
    op.drop_table('arealine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arealine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('custom_description', sa.TEXT(), nullable=True),
    sa.Column('fulfillment_status', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('invoice_date', sa.DATETIME(), nullable=True),
    sa.Column('invoice_status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_delivery_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('arealine_id', sa.INTEGER(), nullable=False),
    sa.Column('nearest_place_id', sa.INTEGER(), nullable=False),
    sa.Column('address_line', sa.VARCHAR(length=500), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('alt_phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('additional_info', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['arealine_id'], ['arealine.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['nearest_place_id'], ['nearest_place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nearest_place',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('arealine_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['arealine_id'], ['arealine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('order_date', sa.DATETIME(), nullable=True),
    sa.Column('expected_delivery_date', sa.DATE(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('custom_description', sa.TEXT(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('arealine_id', sa.INTEGER(), nullable=False),
    sa.Column('nearest_place_id', sa.INTEGER(), nullable=False),
    sa.Column('address_line', sa.VARCHAR(length=500), nullable=False),
    sa.Column('additional_info', sa.TEXT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('delivery_remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['arealine_id'], ['arealine.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['nearest_place_id'], ['nearest_place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
