"""empty message

Revision ID: 7bfdae957786
Revises: be5036d2f0d1
Create Date: 2024-09-20 12:01:53.769886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfdae957786'
down_revision = 'be5036d2f0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_cart_product_id'), ['product_id'], unique=False)
        # Explicitly name the foreign key constraint
        batch_op.create_foreign_key('fk_cart_product_id', 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('quantity_in_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('quantity_in_stock',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_product_id', type_='foreignkey')  # Use the same name for the constraint
        batch_op.drop_index(batch_op.f('ix_cart_product_id'))
        batch_op.drop_column('product_id')
    # ### end Alembic commands ###
