"""Added bought_items relationship to User and tracking for bought_by_admin in OrderItem

Revision ID: 7d04057b28bb
Revises: 84db4338ad68
Create Date: 2024-07-03 19:05:30.946539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d04057b28bb'
down_revision = '84db4338ad68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bought_by_admin_id', sa.Integer(), nullable=True))
        op.create_foreign_key('fk_order_item_user_id', 'order_item', 'user', ['user_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bought_by_admin_id')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('purchase_status')

    # ### end Alembic commands ###
