"""empty message

Revision ID: 84db4338ad68
Revises: 72be40b7df21
Create Date: 2024-06-23 12:50:51.196296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84db4338ad68'
down_revision = '72be40b7df21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('invoice')
    with op.batch_alter_table('user_delivery_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_delivery_info', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('invoice_date', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    # ### end Alembic commands ###
