"""empty message

Revision ID: 88bdf89d58ec
Revises: 6784e8fe4fac
Create Date: 2024-08-23 22:12:20.438334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bdf89d58ec'
down_revision = '6784e8fe4fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_click', schema=None) as batch_op:
        batch_op.drop_index('ix_product_click_guest_ip')
        batch_op.drop_index('ix_product_click_product_id')
        batch_op.drop_index('ix_product_click_timestamp')
        batch_op.drop_index('ix_product_click_user_id')

    op.drop_table('product_click')
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.drop_index('ix_product_view_guest_ip')
        batch_op.drop_index('ix_product_view_product_id')
        batch_op.drop_index('ix_product_view_timestamp')
        batch_op.drop_index('ix_product_view_user_id')

    op.drop_table('product_view')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_message_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('click_count')
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('click_count', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_receiver_id'))
        batch_op.drop_column('read_timestamp')

    op.create_table('product_view',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('guest_ip', sa.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_view', schema=None) as batch_op:
        batch_op.create_index('ix_product_view_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_product_view_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_product_view_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_product_view_guest_ip', ['guest_ip'], unique=False)

    op.create_table('product_click',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('guest_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_click', schema=None) as batch_op:
        batch_op.create_index('ix_product_click_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_product_click_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_product_click_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_product_click_guest_ip', ['guest_ip'], unique=False)

    # ### end Alembic commands ###
