"""empty message

Revision ID: 98cd24592fc7
Revises: d35286bf7caa
Create Date: 2024-06-09 16:13:39.310677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cd24592fc7'
down_revision = 'd35286bf7caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_remarks', sa.Text(), nullable=True))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_remarks')

    # ### end Alembic commands ###
