"""empty message

Revision ID: b621159b39b1
Revises: 498fb5585a64
Create Date: 2024-09-20 12:14:06.516223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b621159b39b1'
down_revision = '498fb5585a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('product_variety_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('product_variety_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
